version: "3"

services:
  polychrom_devx:
    image: nginx:stable-alpine
    build: .
    container_name: spaceframe_io
    ports:
      - 8017
    volumes:
      - ./dist/spaceframe.io:/usr/share/nginx/html

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spaceframe_io.entrypoints=websecure"
      - "traefik.http.routers.spaceframe_io.rule=Host(`spaceframe.io`, `www.spaceframe.io`)"
      - "traefik.http.routers.spaceframe_io.tls.certresolver=myresolver"
      - "traefik.port=8018"

        # Enable gzip compression
      - "traefik.http.routers.spaceframe_io.middlewares=test-compress"
      - "traefik.http.middlewares.test-compress.compress=true"

      #- "traefik.http.middlewares.testheader.headers.accesscontrolmaxage=2628000"


      #- "traefik.http.middlewares.testHeader.headers.customrequestheaders.Cache-Control=no-cache"
      #- "traefik.http.middlewares.testHeader.headers.customrequestheaders.Pragma=no-cache"

      # Cache Ttl 1 month
      - "traefik.http.middlewares.test-http-cache.plugin.httpCache.maxTtl=2628000"
      -

    networks:
      - traefik_network
networks:
  traefik_network:
    external: true
